[package]
name = "sky_combat"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flask = { git = "https://github.com/aegis-dev/flask.git" }
rand = "0.8"
