[package]
name = "sky_combat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flask = { path = "libs/flask" }
wasm-bindgen = "0.2.83"

[lib]
crate-type = ["cdylib"]